version: '2'
services:
  kafka1:
    image: spotify/kafka
    ports:
      - "9092:9092"
    environment:
      ADVERTISED_HOST: "ip route get 1 | awk '{print $NF;exit}'"
      ADVERTISED_PORT: 9092
  kafka2:
    image: spotify/kafka
    ports:
      - "9093:9093"
    environment:
      ADVERTISED_HOST: "ip route get 1 | awk '{print $NF;exit}'"
      ADVERTISED_PORT: 9093
  kafka3:
    image: spotify/kafka
    ports:
      - "9094:9094"
    environment:
      ADVERTISED_HOST: "ip route get 1 | awk '{print $NF;exit}'"
      ADVERTISED_PORT: 9094
